service: expressjs-codespace
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-localstack
  - serverless-resources
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: index.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: /
          method: options
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /{proxy+}
          method: options

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-queue-${opt:stage, 'dev'}

custom:
  serverless-offline:
    host: 0.0.0.0
    noPrependStageInUrl: true
  bundle:
    packager: yarn
