version: '3'
services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-bullseye
    working_dir: /workspace
    volumes:
      - ..:/workspace:cached
    ports:
      - '3000:3000' # serverless-offline
      - '4510-4559:4510-4559' # localstack
      - '4566:4566' # localstack
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  localstack:
    image: localstack/localstack
    restart: unless-stopped
    network_mode: service:workspace
    environment:
      - DEBUG=1
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
     